miProyectoHM/about/urls.py
from django.urls import path, re_path
from .views import about

app_name = 'about'

urlpatterns = [
    path("about/",about,name="about")
]

miProyectoHM/grafo/urls.py
from django.urls import path, re_path
from .views import grafo,procesaGrafo
from . import views

#app_name = 'grafo'

urlpatterns = [
    path('grafo/',grafo,name="grafo"),
    path('procesaGrafo',procesaGrafo,name="procesaGrafo")
]

miProyectoHM/home/urls.py
from django.urls import path
from .views import home

app_name='home'

urlpatterns =[
    path('',home,name='home')
]

miProyectoHM/miProyectoHM/urls.py
from django.contrib import admin
from django.urls import path,include
from home import views 
from sintactico import views
from grafo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('sintactico.urls')),
    path('', include('grafo.urls')),
    path('', include('about.urls')),
    
]

miProyectoHM/sintactico/urls.py
from django.urls import path
from .views import sintactico

#app_name='sintactico'

urlpatterns =[
    path('sintactico/',sintactico,name='sintactico')
]

miProyectoHM/about/models.py
from django.db import models

# Create your models here.

miProyectoHM/grafo/models.py
from django.db import models

# Create your models here.

miProyectoHM/home/models.py
from django.db import models
from django.db.models.fields.related import OneToOneField

# Create your models here.
class Paciente(models.Model):
   # name = models.CharField(max_length=50,blank=True, null=True) #Puede ser nulo
    name = models.CharField(max_length=50)
    
    class Meta:
        verbose_name="Paciente"
        verbose_name_plural="Pacientes"

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse("Paciente_detail",kwargs={"pk":self.pk})


class Tessiu(models.Model):
    temperatura = models.FloatField()
    color=models.FloatField()
    inflammation = models.FloatField(verbose_name='inflamacion')
    #name = models.CharField(max_length=50,blank=True, null=True) #Puede ser nulo
    name=models.ForeignKey(Paciente,blank=True,null=True,verbose_name="nombre",on_delete=models.CASCADE)#LLAVE FORANEA
    #FIELDNAME = models.ManyToManyField(OTHERMODEL) #RELACION MUCHOS A MUCHOS
    #OneToOneField() #RELACIÓN UNO A UNO
    
    class Meta:
       verbose_name=("Tejido")
       verbose_name_plural=("Tejidos")

    def __str__(self):
        if self.name is not None:
            return str(self.temperatura)
        else:
            return str(self.temperatura)

    def get_absolute_url(self):
        return reverse("Tejido_detail",kwargs={"pk":self.pk})

miProyectoHM/sintactico/models.py
from django.db import models

# Create your models here.

miProyectoHM/about/views.py
from django.shortcuts import render

# Create your views here.
def about(request):
    template_name="about/about.html"
    return render(request,template_name,{}) #50:00

miProyectoHM/grafo/views.py
from django.shortcuts import render
from home.models import Tessiu
from scipy.spatial import distance

# Create your views here.
def grafo(request):
    template_name= 'grafo/grafo.html'
    return render(request,template_name,{})


def procesaGrafo(request):
    template_name = "grafo/grafo.html"
    umbral=0
    if request.method  == 'GET':
        umbral=float(request.GET.get('umbral'))
    L = Tessiu.objects.get_queryset()
    listaprocesada = distancia(L,umbral)
    diccionario = {'listap':listaprocesada}
    return render(request, template_name, diccionario)


def distancia(datos,a):
    final = []
    dist = []
    tabla1 = []
    for i in datos:
        dato = []
        dato.append(i.temperatura),dato.append(i.color),dato.append(i.inflammation)
        final.append(dato)      
    
    for i in range(len(final)):
        aux = []
        for j in range(len(final)):
            aux.append(distance.euclidean(final[i],final[j],3))
        dist.append(aux)
    
   
    for i in range(len(dist)):
        for j in range(i,len(dist)):
            v0 = i
            vf = j
            mag = dist[i][j]
            if  mag <= a:
             tabla1.append((v0,vf,mag,"Si"))
            elif mag >= a:
             tabla1.append((v0,vf,mag,"No"))
    return tabla1

miProyectoHM/home/views.py
from django.http.response import HttpResponse
from django.http.response import HttpResponse
from django.shortcuts import render
from .models import Tessiu

# Create your views here.
def home(request):
    L=Tessiu.objects.get_queryset() #Consulta a la base de datos
    template_name="home/index.html"

    listaprocesada=procesaLista()
    
    diccionario={'lista':L,'listaproc':listaprocesada}

    #return render(request,template_name,diccionario)
    return render(request,template_name,{'lista':L})
    #return HttpResponse("Bienvenido Home")

def procesaLista():
    lista1=[]
    a=Tessiu.objects.values('temperatura','color','inflammation')
    #print(a)
    

miProyectoHM/sintactico/views.py
from django.http.response import HttpResponse
from django.shortcuts import render

# Create your views here.
def sintactico(request):
    #print('CORRECTO')
   # return HttpResponse("Sintáctico Estructural...<3")
    template_name="sintactico/sintactico.html"
    return render(request,template_name,{})

miProyectoHM/about/templates/about/about.html
<!DOCTYPE html>
<html>

<head>
    <title>about</title>
    {% extends 'home/index.html' %}

</head>



<body>
    {% block content %}
    <header>
        <div class="content">
            <h1>About Us</h1>
            <hr>
            <h3>UAEM</h3>
        </div>
    </header>

    {% endblock %} {% block contenido %}

    <section>
        <article>
            <h2 align="center"> Centro Universitario UAEM Nezahualcoyotl</h2>
            <hr>
            <p>
                <br>
                <img width="250px" src="https://upload.wikimedia.org/wikipedia/commons/1/1a/Logo_de_la_UAEMex.svg"> Esta página fue creada por estudiantes del Centro Universitario UAEM Nezahualcóyotl, de la carrera de Ingeniería en sistemas inteligentes.
                Como ingenieros nos enfocamos en generar nuevas y mejores soluciones con fundamento en las ciencias de la computación y la inteligencia artificial, los cuales adquieran y procesen datos para encontrar soluciones innovadoras a problemas
                actuales y futuros en cualquier sector y cualquier campo de conocimiento, como es el caso de esta página, centrada al área de la medicina donde se busca generar un impacto y consciencia sobre el tema del cáncer de mama, asimismo facilitando
                el reconocimiento de tejidos cancerosos y sirviendo como soporte o apoyo a dicha área.




            </p>

            <h3>Alumnos</h3>
            <p>*Guerrero Navarrete Osvaldo <br> *Reyes Rosales Nayeli
            </p>
            {% endblock contenido %}
        </article>
    </section>

</body>

</html>

miProyectoHM/grafo/templates/grafo/grafo.html
<!DOCTYPE html>
<html>

<head>
    <title>Grafo</title>

    {% extends 'home/index.html' %}

</head>

<body>
    {% block content %}
    <header>
        <div class="content">
            <h1>Grafo</h1>
            <hr>
            <h3>UAEM</h3>
        </div>
    </header>

    {% endblock %} {% block contenido %}
    <section>
        <article>
            <h2 align="center"> Proceso Del Grafo</h2>
            <hr>
            <p><br>A continuación se muestra el proceso para la creación del grafo, se le solicita al usuario que ingrese el umbral y posteriormente se llenará la tabla, marcando de color verde los registros que se encuentran conectados.
            </p>

            <form action="{% url 'procesaGrafo' %}" method="GET">
                {%csrf_token%}
                <label for="umbral">Umbral</label>
                <input type="text" name="umbral" id="umbral">
                <button class="btn" type="submit" name='miboton'> Iniciar procesamiento</button>
            </form>

            <br>
            <br>
            <table style="border: 1px solid black;">
                <thead>
                    <tr>
                        <th style="border: 1px solid black;">V0</th>
                        <th style="border: 1px solid black;">Vf</th>
                        <th style="border: 1px solid black;">Magnitud</th>
                        <th style="border: 1px solid black;">Conectado</th>
                    </tr>
                </thead>
                <tbody>
                    {% for elemento in listap %}
                    <tr>
                        <td align="center" , style="border: 1px solid black;">{{elemento.0}}</td>

                        <td align="center" , style="border: 1px solid black;">{{elemento.1}}</td>
                        <td align="center" , style="border: 1px solid black;">{{elemento.2}}</td>
                        {% if elemento.3 == "Si" %}
                        <td align="center" , style="border: 1px solid rgb(247, 6, 6); background-color: #DAF7A6;">{{elemento.3}}</td>
                        {% else %}
                        <td align="center" , style="border: 1px solid black;">{{elemento.3}}</td>
                        {% endif %}
                    </tr>
                    {% endfor %}

                </tbody>

            </table>
            {% endblock contenido %}


</body>

</html>

miProyectoHM/home/templates/home/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width-device-width,initial-scale=1.0">
    <title>Home RPSE</title>
    <link rel="icon" type="image/png" href='{% static "/imagenes/favIcon.png" %}'>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>

    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet" />
    <link href='{% static "css/plantilla.css" %}' rel="stylesheet">

    <script type="text/javascript" src='{% static "js/app.js" %}'></script>
</head>

<body>
    <nav id="navbar">
        <div class="content">
            <div class="logo">
                <p>Grafos</p>
                <!--<img src='{% static "/imagenes/logo.png" %}' alt="logotip" width="60">/-->
            </div>
            <div class="menu">

                <a href="{% url 'home:home' %}" class="border">Home</a>
                <a href="{% url 'sintactico' %}" class="border">Sintactico</a>
                <a href="{% url 'grafo' %}" class="border">Grafo</a>
                <a href="{% url 'about:about' %}" class="border">Acerca De </a>



            </div>

        </div>
    </nav>
    {% block content %}
    <header>
        <div class="content">
            <h1>Octubre: Mes Del Cáncer De Mama</h1>
            <h3>La Mejor Lucha Contra El Cáncer Es Una Detección Temprana</h3>
        </div>
    </header>

    {% endblock %} {% block contenido %}
    <section>
        <article>
            <h2 align="center">19 De Octubre. Día Internacional de lucha contra el cáncer de mama</h2>
            <hr>
            <p>
                <img src=https://media2.giphy.com/media/ejawsTkYAGbNsYNbju/200w.webp?cid=ecf05e47qrkekjktxrv5i446ufb0bxeeh7cf2uwty6zwsz8r&rid=200w.webp&ct=s> Fue en 1988 cuando la Organización Mundial de la Salud (OMS) estableció el 19 de octubre como
                el día mundial contra el cáncer de mama, y de acuerdo con cifras de dicho organismo, cada año se diagnostican 1.38 millones de nuevos casos, lo que representa un total de 458,000 fallecimientos a causa de esta enfermedad. Esta fecha pretende
                sensibilizar a la población con un mensaje clave: la importancia de la detección precoz, a fin de mejorar el pronóstico y la supervivencia de los casos de cáncer de mama, lo cual sigue siendo la piedra angular de la lucha contra esta enfermedad.
                Actualmente el cáncer de mama es el más frecuente en las mujeres, tanto en los países desarrollados como en desarrollo. La mayoría de las muertes por cáncer de mama se producen en los países de ingresos bajos y medianos, donde gran parte
                de los casos se diagnostican en un estadio avanzado, sobre todo, por la escasa concienciación y las barreras que dificultan el acceso a los servicios de salud.

            </p>


            <h3>¿Qué es el cáncer de mama? </h3>
            <p>
                El cáncer de mama es un cáncer que se forma en las células de las mamas y puede ocurrir tanto en los hombres como en las mujeres, pero es mucho más frecuente en las mujeres, y ocurre cuando algunas células de la mama comienzan a crecer de manera anormal.
                Estas células se dividen más rápidamente que las células sanas y continúan acumulándose, formando un bulto o tumor. Estas células pueden diseminarse (hacer metástasis) a través de la mama a los ganglios linfáticos o a otras partes del
                cuerpo.
            </p>

            <h3>¿Cuáles son los principales síntomas del cáncer de mama?</h3>
            <p>
                <li>Un bulto o engrosamiento en la mama que se siente diferente del tejido que la rodea.</li>
                <li>Cambio de tamaño, forma o aspecto de una mama.</li>
                <li>Cambios en la piel que se encuentra sobre la mama, como formación de hoyuelos.</li>
                <li>La inversión reciente del pezón.</li>
                <li>Descamación, desprendimiento de la piel, formación de costras y pelado del área pigmentada de la piel que rodea el pezón (areola) o la piel de la mama.</li>
                <li>Enrojecimiento o pequeños orificios en la piel que se encuentra sobre tu mama, como la piel de una naranja.</li>
            </p>

            <p>Descrito lo anterior se pretende hacer uso del reconocimiento de patrones sintactico estructural, y como estudiantes de la Ingeniería En Sistemas Inteligentes realizar un aporte a este problema, es por ello se pretende realizar un estudio
                acerca del cáncer de mama, se hace uso de una base de datos donde contiene las características de los tejidos. A continuación se muestra dicha tabla, también se puede visitar el apartado llamado 'Grafo' donde se emplea el uso del reconocimiento
                de patrones.
            </p>



            <table>
                <thead>
                    <tr>
                        <th>Clave</th>
                        <th>Temperatura</th>
                        <th>Color</th>
                        <th>Inflamacion</th>
                    </tr>
                </thead>
                <tbody>
                    {% for elemento in lista %}
                    <tr>
                        <th>{{elemento.pk}}</th>
                        <th>{{elemento.temperatura}}</th>
                        <th>{{elemento.color}}</th>
                        <th>{{elemento.inflammation}}</th>
                    </tr>
                    {% endfor %}

                </tbody>

            </table>

            {% endblock contenido %}

        </article>
    </section>

    <!--Script-->


</body>

</html>

miProyectoHM/home/templates/home/plantillaP.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width-device-width,initial-scale=1.0">
    <title>{%block title %} {% endblock%}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet" />

    <link href='{% static "css/plantilla.css" %}' rel="stylesheet">

    <script type="text/javascript" src='{% static "js/app.js" %}'></script>
</head>

<body>
    <nav id="navbar">
        <div class="content">
            <div class="logo">
                <p>LOGO</p>
            </div>
            <div class="menu">

                <a href="{% url 'home:home' %}" class="border">Home</a>
                <a href="{% url 'sintactico' %}" class="border">Sintactico</a>
                <a href="{% url 'grafo:grafo' %}" class="border">Grafo</a>
                <a href="{% url 'about:about' %}" class="border">Acerca De </a>



            </div>

        </div>
    </nav>
    {% block content %}
    <header>
        <div class="content">
            <h1></h1>
            <h3></h3>
        </div>
    </header>

    {% endblock %} {% block contenido %}
    <section>
        <article>
            <h2 align="center">19 De Octubre. Día Internacional de lucha contra el cáncer de mama</h2>
            <hr>
            <p><br>Fue en 1988 cuando la Organización Mundial de la Salud (OMS) estableció el 19 de octubre como el día mundial contra el cáncer de mama, y de acuerdo con cifras de dicho organismo, cada año se diagnostican 1.38 millones de nuevos casos,
                lo que representa un total de 458,000 fallecimientos a causa de esta enfermedad. Esta fecha pretende sensibilizar a la población con un mensaje clave: la importancia de la detección precoz, a fin de mejorar el pronóstico y la supervivencia
                de los casos de cáncer de mama, lo cual sigue siendo la piedra angular de la lucha contra esta enfermedad. Actualmente el cáncer de mama es el más frecuente en las mujeres, tanto en los países desarrollados como en desarrollo. La mayoría
                de las muertes por cáncer de mama se producen en los países de ingresos bajos y medianos, donde gran parte de los casos se diagnostican en un estadio avanzado, sobre todo, por la escasa concienciación y las barreras que dificultan el acceso
                a los servicios de salud.
            </p>


            <h3>¿Qué es el cáncer de mama? </h3>
            <p>
                El cáncer de mama es un cáncer que se forma en las células de las mamas y puede ocurrir tanto en los hombres como en las mujeres, pero es mucho más frecuente en las mujeres, y ocurre cuando algunas células de la mama comienzan a crecer de manera anormal.
                Estas células se dividen más rápidamente que las células sanas y continúan acumulándose, formando un bulto o tumor. Estas células pueden diseminarse (hacer metástasis) a través de la mama a los ganglios linfáticos o a otras partes del
                cuerpo.
            </p>

            <h3>¿Cuáles son los principales síntomas del cáncer de mama?</h3>
            <p>
                <li>Un bulto o engrosamiento en la mama que se siente diferente del tejido que la rodea.</li>
                <li>Cambio de tamaño, forma o aspecto de una mama.</li>
                <li>Cambios en la piel que se encuentra sobre la mama, como formación de hoyuelos.</li>
                <li>La inversión reciente del pezón.</li>
                <li>Descamación, desprendimiento de la piel, formación de costras y pelado del área pigmentada de la piel que rodea el pezón (areola) o la piel de la mama.</li>
                <li>Enrojecimiento o pequeños orificios en la piel que se encuentra sobre tu mama, como la piel de una naranja.</li>
            </p>

            <p>Descrito lo anterior se pretende hacer uso del reconocimiento de patrones sintactico estructural, y como estudiantes de la Ingeniería En Sistemas Inteligentes realizar un aporte a este problema, es por ello se pretende realizar un estudio
                acerca del cáncer de mama, se hace uso de una base de datos donde contiene las características de los tejidos. A continuación se muestra dicha tabla, también se puede visitar el apartado llamado 'Grafo' donde se emplea el uso del reconocimiento
                de patrones.
            </p>


            <table>
                <thead>
                    <tr>
                        <th>Clave</th>
                        <th>Temperatura</th>
                        <th>Color</th>
                        <th>Inflamacion</th>
                    </tr>
                </thead>
                <tbody>
                    {% for elemento in lista %}
                    <tr>
                        <th>{{elemento.pk}}</th>
                        <th>{{elemento.temperatura}}</th>
                        <th>{{elemento.color}}</th>
                        <th>{{elemento.inflammation}}</th>
                    </tr>
                    {% endfor %}

                </tbody>

            </table>

            {% endblock contenido %}

        </article>
    </section>

    <!--Script-->


</body>

</html>

miProyectoHM/sintactico/templates/sintactico/sintactico.html
<!DOCTYPE html>
<html>

<head>
    <title>sintaticoE</title>
    {% extends 'home/index.html' %}

</head>


<body>
    {% block content %}
    <header>
        <div class="content">
            <h1>Reconocimiento De Patrones Sintáctico Estructural</h1>
            <hr>
        </div>
    </header>

    {% endblock %} {% block contenido %}

    <section>
        <article>
            <h2 align="center"> ¿Qué Es El Reconocimiento De Patrones?</h2>
            <hr>
            <p><br>
                <img src="https://media3.giphy.com/media/9yRMxLuRqyQ0x3jJXD/200w.webp?cid=ecf05e47keza4z4xl3spllhemx2iue553pj4qvpuy4of4ngi&rid=200w.webp&ct=s"> En este apartado se busca explicar un poco acerca de esta asignatura. El Reconocimiento De
                Patrones se encarga de la descripción y clasificación (reconocimiento) de los procesos sobre ingeniería, computación y matemáticas relacionados con objetos físicos y/o abstractos, personas, señales, representaciones, etc., con el propósito
                de extraer información que permita establecer propiedades de o entre conjuntos de dichos objetos. Esta ciencia trabaja con base en un conjunto previamente establecido de todos los posibles objetos (patrones) individuales a reconocer. El
                margen de aplicaciones del reconocimiento de patrones es muy amplio, sin embargo las más importantes están relacionadas con la visión y audición por parte de una máquina, de forma análoga a los seres humanos.

            </p>

            <p>El objetivo principal de un sistema de reconocimiento automático de patrones es descubrir la naturaleza subyacente de un fenómeno u objeto, describiendo y seleccionado las características fundamentales que permitan clasificarlo en una categoría
                determinada. Son diversos los campos de aplicación que puede tener el tema de esta asignatura: en seguridad, en la medicina, en la industria, en el entretenimiento, en la educación. Y las tareas las que va más orientadas son: de diagnóstico,
                recuperación, predicciones, interpretación, identificación y clasificación de objetos. Principalmente se basa en encontrar las relaciones estructurales que guardan los objetos de estudio, utilizando la teoría de lenguajes formales. El
                objetivo es construir una gramática que describa la estructura del universo de objetos.
                <br>En el reconocimiento sintáctico, cada patrón se describe en términos de sus elementos básicos, y unas reglas sintácticas, llamadas gramática; en conjunto, especifican cómo se pueden generar patrones válidos de una determinada clase.
                El problema se reduce entonces a responder si un determinado patrón pertenece al lenguaje generado por una gramática.</p>

            <p>Se hace uso de Gramáticas Libres De Contexto, las cuales son una especificación para La estructura sintáctica de un lenguaje de programación. Una especificación así es muy similar a la especificación de la estructura léxica de un lenguaje
                utilizando expresiones regulares, excepto que para una gramática libre de contexto involucra reglas de recursividad. </p>


            {% endblock contenido %}

        </article>


        <br>
        <br>
    </section>
</body>

</html>